# SITE CONFIGURATION
title: PyShine # your site title
author: PyShine Team # You :P
description: > # Meta description of Homepage
  AI tutorials
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://py2ai.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: PyShine Team
  links:
    - https://www.facebook.com/py2ai
    - https://www.linkedin.com/in/py2ai/
    - https://github.com/py2ai

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Privacy Policy', link: '/privacy'}
  - {name: 'Disclaimer', link: '/disclaimer'}

tagline: This website provides detailed tutorials on the Artificial Intelligence and its building blocks in Python. The sole purpose is to serve the Humanity.

hero_img: posts/pyshines.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: python2ai@gmail.com # email for form submission

#github_username:  py2ai # replace with your_github_username or comment to remove link from footer
linkedin_username: py2ai
facebook_username: py2ai
google_analytics: 'UA-123748855-1' 

disqus:
  shortname: https-py2ai-github-io # to enable comments replace with your_disqus_shortname
#disqus:
#  shortname: 'https-py2ai-github-io' # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-TCVFBKF # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links


  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
