# SITE CONFIGURATION
title: Guilherme's Blog # your site title
author: Guilherme Duarte Marmerola # You :P
description: > # Meta description of Homepage
  My thoughts and experiments on machine learning and related stuff
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gdmarmerola.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Guilherme Duarte Marmerola
  links:
    - https://www.facebook.com/guimarmerola
    - https://www.linkedin.com/in/gdmarmerola/
    - https://github.com/gdmarmerola

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  My thoughts and experiments on machine learning and related stuff

hero_img: posts/sydney4.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: gdmarmerola@gmail.com # email for form submission

github_username:  gdmarmerola # replace with your_github_username or comment to remove link from footer
linkedin_username: gdmarmerola
facebook_username: guimarmerola

disqus:
  shortname: gdmarmerola # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
